;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	keyboard-escape-quit
	mouse-drag-secondary
	xref-find-definitions
	))

(setq mc/cmds-to-run-once
      '(
	mouse-drag-secondary
	mouse-set-region
	winner-undo
	xref-find-definitions
	))
